# NumPy.

Імпортуйте numpy.

In [1]:
import numpy as np
from pandas import read_csv

##### Створіть масив з 10 нулів:

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##### Створіть масив з 10 одиниць:

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Створіть масив з 10 четвірок:

In [4]:
np.repeat(4,10)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

##### Створіть масив з цілими числами у проміжку від 15 до 30:

In [5]:
print(np.array([i for i in range(15, 31)]))

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


##### Створіть масив з непарних чисел у межах від 15 до 30:

In [6]:
print(np.array([i for i in range(15, 31, 2)]))

[15 17 19 21 23 25 27 29]


##### Створіть матрицю 10 на 10, де числа будуть від 1 до 100:

In [7]:
print(np.array([[i for i in range(j, j + 10)] for j in range(1, 101, 10)]))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


##### Згенеруйте матрицю, як у прикладі:

In [8]:
print(np.array([np.linspace(j, j + 0.09, 10) for j in np.arange(0.01, 1, 0.1)]))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


##### Створіть діагональну матрицю 5 на 5:

In [9]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##### Згенеруйте випадкове число використовуючи NumPy:

In [10]:
np.random.seed(100)  # цей метод доданий, щоб числа, згенеровані випадково були однакові після декількох запусків

random_number = np.random.rand()  # Генеруємо випадкове число від 0 до 1
print(random_number)


0.5434049417909654


##### Згенеруйте масив з 25 випадкових чисел:

In [11]:
np.random.seed(100)

print(np.random.rand(25))

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886 0.12156912
 0.67074908 0.82585276 0.13670659 0.57509333 0.89132195 0.20920212
 0.18532822 0.10837689 0.21969749 0.97862378 0.81168315 0.17194101
 0.81622475 0.27407375 0.43170418 0.94002982 0.81764938 0.33611195
 0.17541045]


##### Створіть масив, у якому 20 чисел лінійно розташовані у проміжку від 0 до 1:

In [12]:
np.random.seed(100)
print(np.linspace(0, 1, 20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


### Індексування.
Необхідно написати код, щоб отримати такі самі дані, як у прикладах з наперед заданої матриці.

In [13]:
matrix = np.arange(0, 25).reshape(5, 5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
x = np.array(matrix)
def submatrix(matrix, startRow, startCol, size):
     return matrix[startRow:startRow+size,startCol:startCol+size]

submatrix(x, 0, 3, 2)

array([[3, 4],
       [8, 9]])

In [18]:
rows, cols = matrix.shape
print(matrix[rows//2, cols//2])

12


In [19]:
matrix[2]

array([10, 11, 12, 13, 14])

## Робота з бібліотекою Pandas.

Імпортуйте pandas.

In [26]:
import pandas as pd

### Завантаження даних у DataFrame.

In [27]:
df = pd.read_csv('Data.csv')

Виведіть перші 10 рядочків з DataFrame.

In [28]:
df.head(10)

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0    8/23/2012  199697               1               1         Brazil   
1     9/7/2016  188693               2               1            NaN   
2    6/24/2013  160026               3               1            NaN   
3    8/24/2015  119109               4               4      Lithuania   
4    4/20/2014  118149               5               5         Canada   
5   11/13/2012  116060               6               4  United States   
6    2/28/2014  114214               7               3          China   
7    11/8/2015  106314               8               8         Russia   
8    6/25/2010  103017               9               6        Austria   
9    7/20/2016  102460              10               9         Latvia   

       Continent  
0  South America  
1            NaN  
2            NaN  
3         Europe  
4  North America  
5  North America  
6           Asia  
7           Asia  
8         Europe  
9         Europe

Виведіть останні 10 рядочків з DataFrame.

In [29]:
df.tail(10)

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
4757    8/29/2010      20            4757              73       Colombia   
4758   11/11/2010      19            4758             117            NaN   
4759   11/24/2011      18            4759            1081            NaN   
4760   11/15/2010      16            4760             151         Israel   
4761    1/17/2012      16            4761            1201  United States   
4762   11/24/2010      14            4762             265        Belgium   
4763     1/1/2012      14            4763            1444            NaN   
4764     1/9/2012      14            4764            1444          India   
4765    1/15/2012      14            4765            1444            NaN   
4766    1/17/2012      14            4766            1444            NaN   

          Continent  
4757  South America  
4758            NaN  
4759            NaN  
4760           Asia  
4761  North America  
4762         Europe  
4763            NaN  
4764           Asia  
4765            NaN  
4766            NaN

Виведіть випадкові 10 рядочків з DataFrame.

In [7]:
df.sample(10)

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
3773    6/20/2013     667            3773             179  United States   
1212    10/7/2016    5481            1212            1111          Spain   
1417     7/5/2017    4677            1417            1025        Ukraine   
1817    3/11/2017    3513            1817            1782         Brazil   
2085   12/30/2015    2921            2085             759            NaN   
2504   10/10/2015    2167            2504             958        Germany   
4076     7/2/2014     461            4076            1083      Australia   
1399   10/23/2011    4726            1399             339            NaN   
1814    8/28/2017    3526            1814            1398          India   
1021    9/13/2016    6578            1021             447         Poland   

          Continent  
3773  North America  
1212         Europe  
1417         Europe  
1817  South America  
2085            NaN  
2504         Europe  
4076        Oceania  
1399            NaN  
1814           Asia  
1021         Europe

Виведіть розмірність DataFrame.

In [9]:
df.shape

(4767, 6)

Виведіть назви колонок DataFrame.

In [10]:
df.columns

Index(['RegisterDate', 'Points', 'CurrentRanking', 'HighestRanking', 'Country',
       'Continent'],
      dtype='object')

Виведіть інформацію про колонку індексів DataFrame.

In [11]:
df.index

RangeIndex(start=0, stop=4767, step=1)

Виведіть інформацію про типи даних елементів у DataFrame.

In [12]:
df.dtypes

RegisterDate      object
Points             int64
CurrentRanking     int64
HighestRanking     int64
Country           object
Continent         object
dtype: object

Створіть нову колонку на основі двох існуючих.

In [14]:
df['NewColumn'] = df['CurrentRanking'] + df['HighestRanking']
df.head()

RegisterDate  Points  CurrentRanking  HighestRanking    Country  \
0    8/23/2012  199697               1               1     Brazil   
1     9/7/2016  188693               2               1        NaN   
2    6/24/2013  160026               3               1        NaN   
3    8/24/2015  119109               4               4  Lithuania   
4    4/20/2014  118149               5               5     Canada   

       Continent  NewColumn  
0  South America          2  
1            NaN          3  
2            NaN          4  
3         Europe          8  
4  North America         10

Виведіть дві будь-які колонки з DataFrame.

In [16]:
df[['CurrentRanking', 'Country']]

CurrentRanking    Country
0                  1     Brazil
1                  2        NaN
2                  3        NaN
3                  4  Lithuania
4                  5     Canada
...              ...        ...
4762            4762    Belgium
4763            4763        NaN
4764            4764      India
4765            4765        NaN
4766            4766        NaN

[4767 rows x 2 columns]

Виведіть рядок з  будь-яким індексом DataFrame.

In [17]:
df.loc[3]

RegisterDate      8/24/2015
Points               119109
CurrentRanking            4
HighestRanking            4
Country           Lithuania
Continent            Europe
NewColumn                 8
Name: 3, dtype: object

Виведіть всі елементи DataFrame, у яких значення колонки 'Country' не є 'None'.

In [18]:
df[df['Country'].notna()]

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0       8/23/2012  199697               1               1         Brazil   
3       8/24/2015  119109               4               4      Lithuania   
4       4/20/2014  118149               5               5         Canada   
5      11/13/2012  116060               6               4  United States   
6       2/28/2014  114214               7               3          China   
...           ...     ...             ...             ...            ...   
4757    8/29/2010      20            4757              73       Colombia   
4760   11/15/2010      16            4760             151         Israel   
4761    1/17/2012      16            4761            1201  United States   
4762   11/24/2010      14            4762             265        Belgium   
4764     1/9/2012      14            4764            1444          India   

          Continent  NewColumn  
0     South America          2  
3            Europe          8  
4     North America         10  
5     North America         10  
6              Asia         10  
...             ...        ...  
4757  South America       4830  
4760           Asia       4911  
4761  North America       5962  
4762         Europe       5027  
4764           Asia       6208  

[3500 rows x 7 columns]

Видаліть будь-який рядочок з DataFrame.

In [20]:
df.drop(index=0)

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
1        9/7/2016  188693               2               1            NaN   
2       6/24/2013  160026               3               1            NaN   
3       8/24/2015  119109               4               4      Lithuania   
4       4/20/2014  118149               5               5         Canada   
5      11/13/2012  116060               6               4  United States   
...           ...     ...             ...             ...            ...   
4762   11/24/2010      14            4762             265        Belgium   
4763     1/1/2012      14            4763            1444            NaN   
4764     1/9/2012      14            4764            1444          India   
4765    1/15/2012      14            4765            1444            NaN   
4766    1/17/2012      14            4766            1444            NaN   

          Continent  NewColumn  
1               NaN          3  
2               NaN          4  
3            Europe          8  
4     North America         10  
5     North America         10  
...             ...        ...  
4762         Europe       5027  
4763            NaN       6207  
4764           Asia       6208  
4765            NaN       6209  
4766            NaN       6210  

[4766 rows x 7 columns]

Видаліть будь-яку колонку з DataFrame.

In [22]:
df.drop(columns='NewColumn')

RegisterDate  Points  CurrentRanking  HighestRanking    Country  \
0       8/23/2012  199697               1               1     Brazil   
1        9/7/2016  188693               2               1        NaN   
2       6/24/2013  160026               3               1        NaN   
3       8/24/2015  119109               4               4  Lithuania   
4       4/20/2014  118149               5               5     Canada   
...           ...     ...             ...             ...        ...   
4762   11/24/2010      14            4762             265    Belgium   
4763     1/1/2012      14            4763            1444        NaN   
4764     1/9/2012      14            4764            1444      India   
4765    1/15/2012      14            4765            1444        NaN   
4766    1/17/2012      14            4766            1444        NaN   

          Continent  
0     South America  
1               NaN  
2               NaN  
3            Europe  
4     North America  
...             ...  
4762         Europe  
4763            NaN  
4764           Asia  
4765            NaN  
4766            NaN  

[4767 rows x 6 columns]

Виведіть рядочки, у яких значення 'CurrentRanking' є '1', '2' та '3'.

In [24]:
df[df['CurrentRanking'].isin([1, 2, 3])]

RegisterDate  Points  CurrentRanking  HighestRanking Country      Continent  \
0    8/23/2012  199697               1               1  Brazil  South America   
1     9/7/2016  188693               2               1     NaN            NaN   
2    6/24/2013  160026               3               1     NaN            NaN   

   NewColumn  
0          2  
1          3  
2          4

Виведіть рядочки, у яких значення 'CurrentRanking' є '1', '2' та '3' та значення 'Country' - 'Brazil'.

In [25]:
df[df['CurrentRanking'].isin([1, 2, 3]) & df['Country'] == 'Brazil']

Empty DataFrame
Columns: [RegisterDate, Points, CurrentRanking, HighestRanking, Country, Continent, NewColumn]
Index: []

RegisterDate  Points  CurrentRanking  HighestRanking Country      Continent
0    8/23/2012  199697               1               1  Brazil  South America

Для подальших завдань, створіть DataFrame, який буде містити перші 10 записів з оригінального DataFrame.

In [64]:
# ваш код тут

Виведіть всі значення з колонки 'HighestRanking' та скільки разів вони зустрічаються.

In [66]:
# ваш код тут

4    3
1    2
5    1
3    1
8    1
6    1
9    1
Name: HighestRanking, dtype: int64

Виведіть усі унікальні значення з колонки 'HighestRanking'.

In [68]:
# ваш код тут

array([1, 4, 5, 3, 8, 6, 9])

Застосуйте функцію map до DataFrame.

In [70]:
# ваш код тут

0           South America
2     Continent not found
3                  Europe
4           North America
5           North America
6                    Asia
7                    Asia
8                  Europe
9                  Europe
10                   Asia
Name: Continent, dtype: object

Відсортуйте дані по колонці 'HighestRanking'.

In [72]:
# ваш код тут

RegisterDate  Points  CurrentRanking  HighestRanking        Country  \
0     8/23/2012  199697               1               1         Brazil   
2     6/24/2013  160026               3               1           None   
6     2/28/2014  114214               7               3          China   
3     8/24/2015  119109               4               4      Lithuania   
5    11/13/2012  116060               6               4  United States   
10    2/16/2011  102417              11               4          Japan   
4     4/20/2014  118149               5               5         Canada   
8     6/25/2010  103017               9               6        Austria   
7     11/8/2015  106314               8               8         Russia   
9     7/20/2016  102460              10               9         Latvia   

        Continent  
0   South America  
2            None  
6            Asia  
3          Europe  
5   North America  
10           Asia  
4   North America  
8          Europe  
7            Asia  
9          Europe

Згрупуйте дані по трьох колонках.

In [74]:
# ваш код тут

RegisterDate  Points  \
Continent     Country       HighestRanking                         
Asia          China         3                          1       1   
              Japan         4                          1       1   
              Russia        8                          1       1   
Europe        Austria       6                          1       1   
              Latvia        9                          1       1   
              Lithuania     4                          1       1   
None          None          1                          1       1   
North America Canada        5                          1       1   
              United States 4                          1       1   
South America Brazil        1                          1       1   

                                            CurrentRanking  
Continent     Country       HighestRanking                  
Asia          China         3                            1  
              Japan         4                            1  
              Russia        8                            1  
Europe        Austria       6                            1  
              Latvia        9                            1  
              Lithuania     4                            1  
None          None          1                            1  
North America Canada        5                            1  
              United States 4                            1  
South America Brazil        1                            1

Застосуйте функції агрегації до даних.

In [76]:
# ваш код тут

Points            1241463
HighestRanking          1
dtype: int64

Застосуйте функцію `query()` до даних.

In [78]:
# ваш код тут

Empty DataFrame
Columns: [RegisterDate, Points, CurrentRanking, HighestRanking, Country, Continent]
Index: []

## Робота з бібліотекою Polars.

### Імпорт бібліотеки. 

### Завантаження даних у DataFrame.

In [81]:
# ваш код тут

shape: (4_767, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---       ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str       ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil    ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None      ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None      ┆ None          │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe        │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada    ┆ North America │
│ …            ┆ …      ┆ …              ┆ …              ┆ …         ┆ …             │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe        │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None      ┆ None          │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia          │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None      ┆ None          │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None      ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴───────────┴───────────────┘

Виведіть перші 10 рядочків з DataFrame.

In [83]:
# ваш код тут

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil        ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None          ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None          ┆ None          │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania     ┆ Europe        │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada        ┆ North America │
│ 11/13/2012   ┆ 116060 ┆ 6              ┆ 4              ┆ United States ┆ North America │
│ 2/28/2014    ┆ 114214 ┆ 7              ┆ 3              ┆ China         ┆ Asia          │
│ 11/8/2015    ┆ 106314 ┆ 8              ┆ 8              ┆ Russia        ┆ Asia          │
│ 6/25/2010    ┆ 103017 ┆ 9              ┆ 6              ┆ Austria       ┆ Europe        │
│ 7/20/2016    ┆ 102460 ┆ 10             ┆ 9              ┆ Latvia        ┆ Europe        │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

Виведіть останні 10 рядочків з DataFrame.

In [85]:
# ваш код тут

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/29/2010    ┆ 20     ┆ 4757           ┆ 73             ┆ Colombia      ┆ South America │
│ 11/11/2010   ┆ 19     ┆ 4758           ┆ 117            ┆ None          ┆ None          │
│ 11/24/2011   ┆ 18     ┆ 4759           ┆ 1081           ┆ None          ┆ None          │
│ 11/15/2010   ┆ 16     ┆ 4760           ┆ 151            ┆ Israel        ┆ Asia          │
│ 1/17/2012    ┆ 16     ┆ 4761           ┆ 1201           ┆ United States ┆ North America │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium       ┆ Europe        │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None          ┆ None          │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India         ┆ Asia          │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None          ┆ None          │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None          ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

Виведіть випадкові 10 рядочків з DataFrame.

In [87]:
# ваш код тут

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 4/30/2015    ┆ 2167   ┆ 2503           ┆ 1231           ┆ Canada        ┆ North America │
│ 4/18/2016    ┆ 2554   ┆ 2268           ┆ 1739           ┆ Italy         ┆ Europe        │
│ 4/16/2012    ┆ 581    ┆ 3904           ┆ 263            ┆ None          ┆ None          │
│ 4/20/2015    ┆ 56483  ┆ 41             ┆ 19             ┆ Canada        ┆ North America │
│ 5/13/2014    ┆ 9933   ┆ 626            ┆ 626            ┆ United States ┆ North America │
│ 7/21/2015    ┆ 2485   ┆ 2305           ┆ 1175           ┆ India         ┆ Asia          │
│ 7/1/2013     ┆ 2123   ┆ 2534           ┆ 1104           ┆ Poland        ┆ Europe        │
│ 7/22/2013    ┆ 5358   ┆ 1241           ┆ 165            ┆ China         ┆ Asia          │
│ 7/2/2010     ┆ 26     ┆ 4750           ┆ 98             ┆ Canada        ┆ North America │
│ 7/3/2011     ┆ 55     ┆ 4712           ┆ 420            ┆ None          ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

Виведіть розмірність DataFrame.

In [89]:
# ваш код тут

(4767, 6)

Виведіть назви колонок DataFrame.

In [91]:
# ваш код тут

['RegisterDate',
 'Points',
 'CurrentRanking',
 'HighestRanking',
 'Country',
 'Continent']

Виведіть інформацію про типи даних елементів у DataFrame.

In [93]:
# ваш код тут

[String, Int64, Int64, Int64, String, String]

Створіть нову колонку на основі двох існуючих.

In [95]:
# ваш код тут

shape: (4_767, 7)
┌──────────────┬────────┬────────────────┬────────────────┬───────────┬───────────────┬───────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent     ┆ NewColumn │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---       ┆ ---           ┆ ---       │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str       ┆ str           ┆ i64       │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════╪═══════════════╪═══════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil    ┆ South America ┆ 2         │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None      ┆ None          ┆ 3         │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None      ┆ None          ┆ 4         │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe        ┆ 8         │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada    ┆ North America ┆ 10        │
│ …            ┆ …      ┆ …              ┆ …              ┆ …         ┆ …             ┆ …         │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe        ┆ 5027      │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None      ┆ None          ┆ 6207      │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia          ┆ 6208      │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None      ┆ None          ┆ 6209      │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None      ┆ None          ┆ 6210      │
└──────────────┴────────┴────────────────┴────────────────┴───────────┴───────────────┴───────────┘

Виведіть дві будь-які колонки з DataFrame.

In [97]:
# ваш код тут

shape: (4_767, 2)
┌────────────────┬───────────┐
│ CurrentRanking ┆ Country   │
│ ---            ┆ ---       │
│ i64            ┆ str       │
╞════════════════╪═══════════╡
│ 1              ┆ Brazil    │
│ 2              ┆ None      │
│ 3              ┆ None      │
│ 4              ┆ Lithuania │
│ 5              ┆ Canada    │
│ …              ┆ …         │
│ 4762           ┆ Belgium   │
│ 4763           ┆ None      │
│ 4764           ┆ India     │
│ 4765           ┆ None      │
│ 4766           ┆ None      │
└────────────────┴───────────┘

Виведіть рядок з  будь-яким індексом DataFrame.

In [99]:
# ваш код тут

('1/17/2012', 41478, 84, 14, 'Netherlands', 'Europe', 98)

Виведіть всі елементи DataFrame, у яких значення колонки 'Country' не є 'None'.

In [101]:
# ваш код тут

shape: (3_500, 7)
┌──────────────┬────────┬────────────────┬────────────────┬───────────┬────────────────┬───────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent      ┆ NewColumn │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---       ┆ ---            ┆ ---       │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str       ┆ str            ┆ i64       │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════╪════════════════╪═══════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil    ┆ South America  ┆ 2         │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe         ┆ 8         │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada    ┆ North America  ┆ 10        │
│ 11/13/2012   ┆ 116060 ┆ 6              ┆ 4              ┆ United    ┆ North America  ┆ 10        │
│              ┆        ┆                ┆                ┆ States    ┆                ┆           │
│ 2/28/2014    ┆ 114214 ┆ 7              ┆ 3              ┆ China     ┆ Asia           ┆ 10        │
│ …            ┆ …      ┆ …              ┆ …              ┆ …         ┆ …              ┆ …         │
│ 8/29/2010    ┆ 20     ┆ 4757           ┆ 73             ┆ Colombia  ┆ South America  ┆ 4830      │
│ 11/15/2010   ┆ 16     ┆ 4760           ┆ 151            ┆ Israel    ┆ Asia           ┆ 4911      │
│ 1/17/2012    ┆ 16     ┆ 4761           ┆ 1201           ┆ United    ┆ North America  ┆ 5962      │
│              ┆        ┆                ┆                ┆ States    ┆                ┆           │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe         ┆ 5027      │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia           ┆ 6208      │
└──────────────┴────────┴────────────────┴────────────────┴───────────┴────────────────┴───────────┘

Видаліть будь-яку колонку з DataFrame.

In [103]:
# ваш код тут

shape: (4_767, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country   ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---       ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str       ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil    ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None      ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None      ┆ None          │
│ 8/24/2015    ┆ 119109 ┆ 4              ┆ 4              ┆ Lithuania ┆ Europe        │
│ 4/20/2014    ┆ 118149 ┆ 5              ┆ 5              ┆ Canada    ┆ North America │
│ …            ┆ …      ┆ …              ┆ …              ┆ …         ┆ …             │
│ 11/24/2010   ┆ 14     ┆ 4762           ┆ 265            ┆ Belgium   ┆ Europe        │
│ 1/1/2012     ┆ 14     ┆ 4763           ┆ 1444           ┆ None      ┆ None          │
│ 1/9/2012     ┆ 14     ┆ 4764           ┆ 1444           ┆ India     ┆ Asia          │
│ 1/15/2012    ┆ 14     ┆ 4765           ┆ 1444           ┆ None      ┆ None          │
│ 1/17/2012    ┆ 14     ┆ 4766           ┆ 1444           ┆ None      ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴───────────┴───────────────┘

Виведіть рядочки, у яких значення 'CurrentRanking' є '1', '2' та '3'.

In [105]:
# ваш код тут

shape: (3, 6)
┌──────────────┬────────┬────────────────┬────────────────┬─────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---     ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str     ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil  ┆ South America │
│ 9/7/2016     ┆ 188693 ┆ 2              ┆ 1              ┆ None    ┆ None          │
│ 6/24/2013    ┆ 160026 ┆ 3              ┆ 1              ┆ None    ┆ None          │
└──────────────┴────────┴────────────────┴────────────────┴─────────┴───────────────┘

Виведіть рядочки, у яких значення 'CurrentRanking' є '1', '2' та '3' та значення 'Country' - 'Brazil'.

In [107]:
# ваш код тут

shape: (1, 6)
┌──────────────┬────────┬────────────────┬────────────────┬─────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---     ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str     ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═════════╪═══════════════╡
│ 8/23/2012    ┆ 199697 ┆ 1              ┆ 1              ┆ Brazil  ┆ South America │
└──────────────┴────────┴────────────────┴────────────────┴─────────┴───────────────┘

Для подальших завдань, створіть DataFrame, який буде містити випадкові 10 записів з оригінального DataFrame.

In [109]:
# ваш код тут

Виведіть всі значення з колонки 'HighestRanking' та скільки разів вони зустрічаються.

In [111]:
# ваш код тут

shape: (10, 2)
┌────────────────┬───────┐
│ HighestRanking ┆ count │
│ ---            ┆ ---   │
│ i64            ┆ u32   │
╞════════════════╪═══════╡
│ 616            ┆ 1     │
│ 666            ┆ 1     │
│ 865            ┆ 1     │
│ 46             ┆ 1     │
│ 2080           ┆ 1     │
│ 189            ┆ 1     │
│ 251            ┆ 1     │
│ 373            ┆ 1     │
│ 902            ┆ 1     │
│ 511            ┆ 1     │
└────────────────┴───────┘

Виведіть усі унікальні значення з колонки 'HighestRanking'.

In [113]:
# ваш код тут

shape: (10,)
Series: 'HighestRanking' [i64]
[
	46
	189
	251
	373
	511
	616
	666
	865
	902
	2080
]

Застосуйте функцію map до DataFrame.

In [115]:
# ваш код тут

shape: (10,)
Series: 'Continent' [str]
[
	"Continent not found"
	"Asia"
	"Europe"
	"North America"
	"Asia"
	"North America"
	"North America"
	"North America"
	"Continent not found"
	"Asia"
]

Відсортуйте дані по колонці 'HighestRanking'.

In [117]:
# ваш код тут

shape: (10, 6)
┌──────────────┬────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ RegisterDate ┆ Points ┆ CurrentRanking ┆ HighestRanking ┆ Country       ┆ Continent     │
│ ---          ┆ ---    ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│ str          ┆ i64    ┆ i64            ┆ i64            ┆ str           ┆ str           │
╞══════════════╪════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 8/19/2012    ┆ 6464   ┆ 1040           ┆ 46             ┆ United States ┆ North America │
│ 2/5/2016     ┆ 23460  ┆ 210            ┆ 189            ┆ United States ┆ North America │
│ 11/23/2010   ┆ 45     ┆ 4727           ┆ 251            ┆ Netherlands   ┆ Europe        │
│ 12/2/2015    ┆ 15131  ┆ 380            ┆ 373            ┆ Japan         ┆ Asia          │
│ 3/23/2014    ┆ 1788   ┆ 2763           ┆ 511            ┆ United States ┆ North America │
│ 3/4/2013     ┆ 4827   ┆ 1363           ┆ 616            ┆ Japan         ┆ Asia          │
│ 4/29/2015    ┆ 7504   ┆ 879            ┆ 666            ┆ None          ┆ None          │
│ 5/22/2016    ┆ 6243   ┆ 1077           ┆ 865            ┆ None          ┆ None          │
│ 12/27/2014   ┆ 2974   ┆ 2050           ┆ 902            ┆ Thailand      ┆ Asia          │
│ 2/23/2017    ┆ 2378   ┆ 2361           ┆ 2080           ┆ United States ┆ North America │
└──────────────┴────────┴────────────────┴────────────────┴───────────────┴───────────────┘

Згрупуйте дані по трьох колонках.

In [119]:
# ваш код тут

shape: (10, 4)
┌───────────────┬───────────────┬────────────────┬─────┐
│ Continent     ┆ Country       ┆ HighestRanking ┆ len │
│ ---           ┆ ---           ┆ ---            ┆ --- │
│ str           ┆ str           ┆ i64            ┆ u32 │
╞═══════════════╪═══════════════╪════════════════╪═════╡
│ North America ┆ United States ┆ 2080           ┆ 1   │
│ North America ┆ United States ┆ 511            ┆ 1   │
│ None          ┆ None          ┆ 666            ┆ 1   │
│ Asia          ┆ Japan         ┆ 373            ┆ 1   │
│ Asia          ┆ Japan         ┆ 616            ┆ 1   │
│ North America ┆ United States ┆ 46             ┆ 1   │
│ None          ┆ None          ┆ 865            ┆ 1   │
│ Asia          ┆ Thailand      ┆ 902            ┆ 1   │
│ North America ┆ United States ┆ 189            ┆ 1   │
│ Europe        ┆ Netherlands   ┆ 251            ┆ 1   │
└───────────────┴───────────────┴────────────────┴─────┘

Застосуйте функції агрегації до даних.

In [121]:
# ваш код тут

shape: (4, 2)
┌───────────────┬───────┐
│ Continent     ┆ range │
│ ---           ┆ ---   │
│ str           ┆ i64   │
╞═══════════════╪═══════╡
│ Europe        ┆ 0     │
│ None          ┆ 198   │
│ North America ┆ 2553  │
│ Asia          ┆ 1670  │
└───────────────┴───────┘