# NumPy.

NumPy (або Numpy) це бібліотека лінійної алгебри для Python. Більшість бібліотек у екосистемі PyData залежить від NumPy як одного з основних блоків.

#### Використання NumPy.

In [1]:
import numpy as np

#### Масиви NumPy.

Масиви NumPy зазвичай представлені у двох виглядах: вектори та матриці. Вектори це одновимірні масиви, коли матриці це двохвимірні (хоча варто зазначити, що бувають випадки, коли матриці можуть мати один рядочок або одну колонку).
NumPy оптимізований для процесора, що робить його значно швидшим при роботі з великими типами даних. Окрім того, NumPy використовує компактніше представлення даних, що робить його економнішим з точки зору пам'яті.

#### Створення NumPy масивів.

##### Зі звичайних масивів.
Для цього використовується метод [np.array()](https://numpy.org/doc/stable/reference/generated/numpy.array.html).

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### З допомогою вбудованих методів.

##### [arange()](https://numpy.org/doc/stable/reference/generated/numpy.arange.html).
Повертає масив, заповнений рівномірно розподіленими значеннями в межах заданого інтервалу.

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

##### [zeros()](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) i [ones()](https://numpy.org/doc/stable/reference/generated/numpy.ones.html).
Ці методи генерують масиви заповнені нулями та одиницями відповідно.

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### [linspace()](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html).
Повертає масив, заповнений рівномірно розподіленими значеннями у заданому інтервалі.

In [12]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### [repeat()](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html)
Повторює елементи у масиві вказану кількість разів.

In [14]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [15]:
np.array([[1,2],[3,4]]).repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [16]:
np.repeat(np.array([[1,2],[3,4]]), [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

### [tile()](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)
Повторює масив вказану кількість разів.

In [17]:
np.tile(np.array([0, 1, 2]), 2)

array([0, 1, 2, 0, 1, 2])

In [18]:
np.tile(np.array([[1, 2], [3, 4]]), 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [19]:
np.tile(np.array([1,2,3,4]), [1, 4])

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

In [20]:
np.tile(np.array([1,2,3,4]), [4, 1])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

##### [eye()](https://numpy.org/devdocs/reference/generated/numpy.eye.html).
Створює діагональну матрицю.

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Random.
NumPy дозволяє створювати масиви, які заповнені випадковими числами.

##### [rand()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html).
Створює масив вказаної форми і наповнює його випадковими значеннями з рівномірним розподілом у межах [0, 1).

In [22]:
np.random.rand(3)

array([0.29753825, 0.23756852, 0.54012664])

In [23]:
np.random.rand(2, 2)

array([[0.05212444, 0.44738833],
       [0.05781072, 0.28496255]])

##### [randn()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html).

Повертає масив заповнений випадковими значеннями з стандартним нормальним розподілом.

In [24]:
np.random.randn(3)

array([ 0.17787548, -0.40380975,  1.11780196])

In [25]:
np.random.randn(2, 2)

array([[ 0.49314001, -0.2437382 ],
       [ 0.36906683,  1.63553592]])

##### [randint()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html).
Повертає масив заповнений цілими числами з нижньої (включно) до верхньої (невключно) межі.

In [26]:
np.random.randint(1, 100)

36

In [27]:
np.random.randint(1, 100, 50)

array([71,  1, 51, 17, 22, 94, 72, 22, 51, 39, 83, 30, 36, 29, 68, 26, 71,
       72, 38, 35, 40, 26, 92, 63, 63, 19, 10, 19, 17, 88, 31, 39, 79, 45,
       66, 76, 47, 43, 88, 78, 18, 55, 75, 97, 19, 32, 17, 88, 87, 46])

##### [seed()](https://numpy.org/doc/1.25/reference/random/generated/numpy.random.seed.html).
NumPy довзоляє задати число, яке дозволить у майбутньому повторити випадкові результати.

In [28]:
np.random.seed(100)

#### Властивості та методи NumPy масивів.

##### [shape](https://numpy.org/doc/stable/reference/generated/numpy.shape.html)/[reshape()](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html).

In [29]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
arr.shape

(9,)

In [31]:
arr.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr.reshape(3, 3).shape

(3, 3)

In [33]:
arr.reshape(9, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### [flatten](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html)
Повертає копію масиву, з одиничною розмірністю.

In [34]:
np.array([[1,2], [3,4]]).flatten('C')

array([1, 2, 3, 4])

In [35]:
np.array([[1,2], [3,4]]).flatten('F')

array([1, 3, 2, 4])

##### [dtype](https://numpy.org/doc/stable/reference/generated/numpy.dtype.html).
Вказує тип об'єктів у масиві.

In [36]:
arr.dtype

dtype('int64')

##### Корисні функції.

In [37]:
arr = np.random.randint(0, 100, 10)
arr

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98])

In [38]:
arr.max()

98

In [39]:
arr.argmax()

9

In [40]:
arr.min()

8

In [41]:
arr.argmin()

0

### Базові математичні операції.

In [42]:
arr = np.array([1, 2, 3, 4, 5])

Сума усіх елементів масиву:

In [43]:
np.sum(arr)

15

Добуток усіх елементів масиву.

In [44]:
np.prod(arr)

120

Кумулятивна сума усіх елементів масиву.

In [45]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

Кумулятивний добуток усіх елементів масиву.

In [46]:
np.cumprod(arr)

array([  1,   2,   6,  24, 120])

### Базові статистичні функції.

Середнє значення.

In [47]:
np.mean(arr)

3.0

Медіана.

In [48]:
np.median(arr)

3.0

Стандартне відхилення.

In [49]:
np.std(arr)

1.4142135623730951

Дисперсія.

In [50]:
np.var(arr)

2.0

### Робота з матрицями.

In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

Транспонування матриць.

In [52]:
A

array([[1, 2],
       [3, 4]])

In [53]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

Скалярний добуток векторів.

In [54]:
np.dot(a, b)

32

Матричне множення.

In [55]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

Визначник матриці.

In [56]:
np.linalg.det(A)

-2.0000000000000004

Створення оберненої матриці.

In [57]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Власні значення та вектори.

In [58]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

Ранг матриці.

In [59]:
np.linalg.matrix_rank(A)

2

Слід матриці.

In [60]:
np.trace(A)

5

### Розв'язання системи лінійних рівнянь.

In [61]:
# x + 2y = 5
# 3x + 4y = 11

A = np.array([[1, 2],
              [3, 4]])
b = np.array([5, 11])

np.linalg.solve(A, b)

array([1., 2.])

#### Індексування.
Індексування квадратними дужками.

In [62]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr[8]

8

In [64]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [65]:
matrix = np.array(([0, 1, 2],[3, 4, 5],[6, 7, 8]))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
matrix[0]

array([0, 1, 2])

In [67]:
matrix[0, 1]

1

In [68]:
matrix[0][1]

1

In [69]:
matrix[:1, 1:]

array([[1, 2]])

In [70]:
matrix[[0, 2]]

array([[0, 1, 2],
       [6, 7, 8]])

In [71]:
matrix[[2, 0]]

array([[6, 7, 8],
       [0, 1, 2]])

Сортування.

In [72]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

In [73]:
np.sort(arr)

array([1, 1, 2, 3, 3, 4, 5, 5, 6, 9])

In [74]:
np.sort(arr)[::-1]

array([9, 6, 5, 5, 4, 3, 3, 2, 1, 1])

Пошук унікальних елементів.

In [75]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 9])

#### NumPy  у пам'яті.

In [76]:
arr

array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

In [77]:
arr[1:4] = 25
arr

array([ 3, 25, 25, 25,  5,  9,  2,  6,  5,  3])

In [78]:
slice_of_arr = arr[:6]
slice_of_arr

array([ 3, 25, 25, 25,  5,  9])

In [79]:
slice_of_arr[:] = 32
slice_of_arr

array([32, 32, 32, 32, 32, 32])

In [80]:
arr

array([32, 32, 32, 32, 32, 32,  2,  6,  5,  3])

In [81]:
copy = arr.copy()
copy

array([32, 32, 32, 32, 32, 32,  2,  6,  5,  3])

#### Трансляція.
NumPy відрізняється від звичайних Python масивів своїм вмінням транслювати.
Трансляція надає засоби для векторних операцій на масиві таким чином, що цикли відбуваються у С замість Python. Це відбувається без додаткових копій.

Трансляція довзовляє виконувати різні арифметичні операції над масивами. Важливо, щоб масиви були або однаковими у розмірах, або один з елементів мав тільки одне значення.

In [82]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [84]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [86]:
arr / arr

/var/folders/5f/35rhngxj0j3_0r30ftv5dk100000gn/T/ipykernel_27778/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [87]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### Вибір.
Вибір, який базується на операції порівння:

In [88]:
arr > 6

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [89]:
criteria_array = arr > 6
criteria_array

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [90]:
arr[criteria_array]

array([7, 8, 9])

In [91]:
arr[arr > 6]

array([7, 8, 9])

Пошук ненульових елементів.

In [92]:
np.nonzero(arr)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)

### Умовні операції.

[clip()](https://numpy.org/doc/stable/reference/generated/numpy.clip.html) обмежує значення елементів у масиві.

In [93]:
np.clip(arr, 2, 8)

array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8])

[where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html) дозволяє створити новий масив на основі існуючого, і заповнити його певними значеннями згідно з заданою умовою

In [94]:
np.where(arr > 5, 1, 0)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

### [all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html)
Перевіряє, чи всі елементи в масиві виконують задану умову.

In [95]:
arr = np.array([True, True, False])
np.all(arr)

False

In [96]:
arr = np.array([True, True, True])
np.all(arr)

True

### [any()](https://numpy.org/doc/stable/reference/generated/numpy.any.html)
Перевіряє, чи хоча б один елемент у масиві задовільняє задану умову.

In [97]:
arr = np.array([True, True, False])
np.any(arr)

True

In [98]:
arr = np.array([False, False, False])
np.any(arr)

False

#### Функції, універсальні для NumPy масивів
NumPy містить у собі багато функцій, які є математичним операціями, які можна застосовувати до масиву.

In [99]:
np.sqrt(arr)

array([0., 0., 0.], dtype=float16)

In [100]:
np.exp(arr)

array([1., 1., 1.], dtype=float16)

In [101]:
np.max(arr)

False

In [102]:
np.sin(arr)

array([0., 0., 0.], dtype=float16)

## Об'єднання масивів.

### [concatenate()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)
Об'єднує масиви вздовж існуючої осі.

In [103]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

np.concatenate((array1, array2))

array([1, 2, 3, 4, 5, 6])

In [104]:
array1 = np.array([[1, 2],
                  [3, 4]])

array2 = np.array([[5, 6],
                  [7, 8]])

np.concatenate((array1, array2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [105]:
np.concatenate((array1, array2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### [vstack()](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) та [hstack()](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html)

Об'єднує масиви вертикально та горизонтально відповідно.

In [106]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
np.vstack((array1, array2))


array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
np.hstack((array1, array2))

array([1, 2, 3, 4, 5, 6])

## Розділення масиву.
### [split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)
Розділяє масив на сукупність підмасивів.

In [108]:
array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

np.split(array, 3, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]